const hotels = [
  {
    id: 1,
    name: "The Restroom",
    location: "Lapaz",
    rating: 5,
    price: 3,
    reviews: 129,
  },
  {
    id: 2,
    name: "LongeM",
    location: "Paris",
    rating: 4.5,
    price: 4,
    reviews: 247,
  },
  {
    id: 3,
    name: "Le Betivo",
    location: "Cannes",
    rating: 4.0,
    price: 5,
    reviews: 136,
  },
  {
    id: 5,
    name: "La maison des artistes",
    location: "Paris",
    rating: 4.5,
    price: 5,
    reviews: 431,
  },
  {
    id: 6,
    name: "Appart Hotel Amsterdam",
    location: "Amsterdam",
    rating: 4.5,
    price: 4,
    reviews: 325,
  },
  {
    id: 7,
    name: "Hotel de la montre",
    location: "Genève",
    rating: 5,
    price: 5,
    reviews: 189,
  },
  {
    id: 8,
    name: "Le quatre vins",
    location: "Grenoble",
    cuisine: ["Gastronomique"],
    rating: 4.5,
    price: 4,
    reviews: 77,
  },
  {
    id: 9,
    name: "City Hotel",
    location: "Grenoble",
    rating: 3.5,
    price: 3,
    reviews: 110,
  },
  {
    id: 10,
    name: "Stay in London",
    location: "Londres",
    rating: 4,
    price: 3,
    reviews: 204,
  },
  {
    id: 11,
    name: "Relax Hotel",
    location: "Phoenix",
    rating: 4.5,
    price: 4,
    reviews: 387,
  },
  {
    id: 12,
    name: "Xenodocheio",
    location: "Héraklion",
    rating: 4.5,
    price: 4,
    reviews: 177,
  },
  {
    id: 13,
    name: "The little bird Hotel",
    location: "Bangkok",
    rating: 3,
    price: 3,
    reviews: 298,
  },
  {
    id: 14,
    name: "The great palace Hotel",
    location: "Las Vegas",
    rating: 4.5,
    price: 5,
    reviews: 431,
  },
  {
    id: 15,
    name: "The cocoon spa Hotel",
    location: "Bali",
    rating: 4,
    price: 3,
    reviews: 325,
  },
  {
    id: 16,
    name: "Amaterasu Hotel",
    location: "Tokyo",
    rating: 4.5,
    price: 4,
    reviews: 189,
  },
  {
    id: 17,
    name: "",
    location: "",
    rating: 5,
    price: 4,
    reviews: 77,
  },
  {
    id: 18,
    name: "",
    location: "",
    rating: 4.5,
    price: 4,
    reviews: 110,
  },
  {
    id: 19,
    name: "",
    location: "",
    rating: 3.5,
    price: 2,
    reviews: 204,
  },
  {
    id: 20,
    name: "",
    location: "",
    rating: 4.5,
    price: 3,
    reviews: 387,
  },
  {
    id: 21,
    name: "",
    location: "",
    rating: 4.5,
    price: 2,
    reviews: 17,
  },
  { id: 22, name: "", location: "", rating: 4, price: 3, reviews: 110 },
  { id: 23, name: "", location: "", rating: 3.5, price: 2, reviews: 204 },
  { id: 24, name: "", location: "", rating: 4.5, price: 3, reviews: 387 },
  { id: 25, name: "", location: "", rating: 4.5, price: 2, reviews: 17 },
  { id: 26, name: "", location: "", rating: 4, price: 3, reviews: 110 },
  { id: 27, name: "", location: "", rating: 3.5, price: 2, reviews: 204 },
  { id: 28, name: "", location: "", rating: 4.5, price: 3, reviews: 387 },
  { id: 29, name: "", location: "", rating: 4.5, price: 2, reviews: 17 },
  { id: 30, name: "", location: "", rating: 4, price: 3, reviews: 110 },
  { id: 31, name: "", location: "", rating: 3.5, price: 2, reviews: 204 },
  { id: 32, name: "", location: "", rating: 4.5, price: 3, reviews: 387 },
  { id: 33, name: "", location: "", rating: 4.5, price: 2, reviews: 17 },
  { id: 34, name: "", location: "", rating: 4, price: 3, reviews: 110 },
  { id: 35, name: "", location: "", rating: 3.5, price: 2, reviews: 204 },
  { id: 36, name: "", location: "", rating: 4.5, price: 3, reviews: 387 },
  { id: 37, name: "", location: "", rating: 4, price: 5, reviews: 478 }
];

module.exports = { hotels };
